name: Warriors
version: "\u001B[35mClosed Beta\u001B[0m"
main: plugin.Main
api-version: 1.19
commands:
  heal:
    permission: permission.mod
  kit:
  sign:
  fix:
  uwu:
  invsee:
  spawn:
  workbench:
    aliases: "wb"
  anvil:
  specialitems:
    aliases: "items"
  vanish:
    aliases: "v"
    permission: permission.mod
  stats:
  shop:
    aliases: 'laden'
  trash:
    aliases: "müll"
  xp:
    aliases: "erfahrungspunkte"
  modify:
    aliases: "modifizieren"
  top:
  perks:
  infobar:
  crate:
    permission: permission.mod
  nightvision:
    aliases: ['nv', 'nachtsicht']
  setrank:
    permission: permission.mod
  safe:
    aliases: ['tr', 'tresor']
  kick:
    aliases: ['punish']
    permission: permission.mod
  cps:
    permission: permission.mod

permissions:
  permission.mod:
    default: op